/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args){
	//test code for Deck and Card classes

	//create new deck object
        Deck deck = new Deck();
	//loop through deck and check that each card is created properly
	System.out.println("Testing dealing cards with deck in order.\n");
	for(int i=0; i<52; i++){
		//should successfully deal each card in order
		Card temp = deck.dealOneCard();
		System.out.println(temp.getvalue() + " of " + temp.getsuit());
	}
	//use the shuffle function
	System.out.println("\n\nShuffling...\n");
	deck.shuffle();
	//test that the cards are now randomly permuted
	System.out.println("Testing dealing cards with deck shuffled.\n");
	for(int i=0; i<52; i++){
		Card temp = deck.dealOneCard();
		System.out.println(temp.getvalue() + " of " + temp.getsuit());
	}
    }
}
